#!/bin/bash
VERSION=`grep s.version logstash-output-OMS.gemspec | awk -F'"' '{print $2}'`
gem build logstash-output-OMS.gemspec
/opt/logstash/bin/plugin install logstash-output-OMS-${VERSION}.gem
/opt/logstash/bin/logstash -f /etc/logstash/conf.d/oms-pipeline.conf
